"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#a3aed2)\
[  $os ](bg:#a3aed2 fg:#090c0c)\
[](bg:#5884db fg:#a3aed2)\
$directory\
[](fg:#5884db bg:#394260)\
$hostname\
[](fg:#394260 bg:#1d2230)\
$time\
[ ](fg:#1d2230)\
\n$character"""

[directory]
style = "fg:#ffffff bg:#5884db"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#394260"
format = '[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)'

[git_status]
style = "bg:#394260"
format = '[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)'

[hostname]
ssh_only = false
style = "bg:#394260"
format = '[[  $hostname ](fg:#ffffff bg:#394260)]($style)'
disabled = false

[time]
disabled = false
time_format = "%I:%M%P"
style = "bg:#1d2230"
format = '[[ 🕙 $time ](fg:#dae6fc bg:#1d2230)]($style)'

[character]
success_symbol = "[   ](bold green) "
#success_symbol = "[[✔](bold green) [  ] "
error_symbol = "[   ](bold red) "
#error_symbol = "[ 💀 ](bold blue) "   

[os]
disabled = false
style = "bg:red fg:crust"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
